### ISSUE TITLE
[Fix] 403 에러 수정

### ISSUE THREAD

**Issue by runasy-koonta** [Me1tingPot/BE#50]
## 요약
Spring Security 관련해 올바른 토큰이 제공되었는데도 403이 표출되는 문제를 수정한다.

<br><br>

## 작업 내용
- [x] token 검증 코드 수정

<br><br>

## 참고 사항

<br><br>

**Comment by runasy-koonta** [comment]
@JangYouJung 코드 확인 후 문제 없으면 issue close 부탁드립니다!

**Comment by JangYouJung** [comment]
> @JangYouJung 코드 확인 후 문제 없으면 issue close 부탁드립니다!

넵 확인했습니다!
